version: '3.2'
services:
  redis:
    container_name: redis
    image: "redis"
    ports:
      - "7001:6379"
    networks:
      mynet:
        ipv4_address: 172.25.0.101

  app_web_flask_offer:
    build:
      context: ../Python_Web_Server
      dockerfile: Dockerfile
    image: "app_web_flask_offer"
    ports:
     - "7070:8080"
    links:
      - redis
    depends_on:
      - redis
    networks:
      mynet:
        ipv4_address: 172.25.0.102

networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
